### ISSUE TITLE
Deleting Font-level and Glyph-level guides at the same time produces a traceback

### ISSUE THREAD

**Issue by colinmford** [typesupply/guidetool#19]
I am getting a traceback when deleting font-level and glyph-level guides together. Tool still allows me to delete them separately, so this is pretty minor.

Reproduce:
1. Drag in a glyph-level guide from edge
2. Hold cmd, drag in a font-level guide from edge
3. Select both and hit delete key

Traceback:
```Traceback (most recent call last):
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/tool.py", line 555, in keyDown
AttributeError: 'NoneType' object has no attribute 'undo'
```

The [Line 555](https://github.com/typesupply/guidetool/blob/dcdbed6167d899901c085ff491c786c08834f2c9/build/Guide%20Tool.roboFontExt/lib/guideTool/tool.py#L555) in question.

Possibly related to #8 ?

**Comment by typesupply** [comment]
This should be fixed. Thanks!

**Comment by colinmford** [comment]
LGTM!
