### ISSUE TITLE
"Add Glyph/Font Guide" when only one node is selected

### ISSUE THREAD

**Issue by colinmford** [typesupply/guidetool#20]
Currently if you only have one node selected and you execute either the "Add Glyph Guide" or "Add Font Guide" scripts from the extension menu, it creates a guideline at (0,0) with angle 0. I would say this is a bug? Does it work for anyone else?

I would expect at least a vertical (or italic angle) guide at the location of the node. An enhancement that might be cool would be if the guide could follow the angle of the handles if it's a smooth point (maybe behavior that could be toggled in preferences).

@typesupply if this is something you would like I could attempt a PR.

**Comment by typesupply** [comment]
Try the build in the development branch. I wasn't handling all of the possibilities in the `guideTool.guess.guessPositionAndAngleFromSelectedPoints` function.

**Comment by colinmford** [comment]
Works perfectly for me! Thanks, @typesupply (also the other issue is fixed as well)
