### ISSUE TITLE
Add some kind of smart settings.

### ISSUE THREAD

**Issue by typesupply** [typesupply/guidetool#4]
Issues:

1. It needs an editor. Rule editors are complicated. Maybe start with a simple text editor instead of a full blown rule editor? With abbreviated categories, blocks, etc?

```
name: *.sc
unicodeblock: latin
unicodecategory: uppercase, number
```

2. How can I make guides that don't match the glyph invisible? (Maybe @typemytype has an idea?)

**Comment by typemytype** [comment]
good question...

there is now no way to "hide" a guideline. 

adding and removing a guideline seems silly.
I guess RF could add a lib key to show/hide guidelines, like `showMeasurements` and `magnetic` are added attributes
